---
name: Enlarge version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: '0'
      - name: Enlarge version and push tag
        uses: tenantcloud/tagger@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
